export const userList = [
  {
    id: 1,
    firstName: 'Jan',
    lastName: 'Kowalski',
    age: 30,
    postalCode: '00-001',
  },
  {
    id: 2,
    firstName: 'Anna',
    lastName: 'Nowak',
    age: 25,
    postalCode: '11-111',
  },
  {
    id: 3,
    firstName: 'Piotr',
    lastName: 'Wiśniewski',
    age: 35,
    postalCode: '22-222',
  },
  {
    id: 4,
    firstName: 'John',
    lastName: 'Doe',
    age: 28,
    postalCode: '33-333',
  },
  {
    id: 5,
    firstName: 'Emily',
    lastName: 'Smith',
    age: 22,
    postalCode: '44-444',
  },
  {
    id: 6,
    firstName: 'Michael',
    lastName: 'Johnson',
    age: 40,
    postalCode: '55-555',
  },
  {
    id: 7,
    firstName: 'Sophia',
    lastName: 'Williams',
    age: 32,
    postalCode: '66-666',
  },
  {
    id: 8,
    firstName: 'Daniel',
    lastName: 'Brown',
    age: 26,
    postalCode: '77-777',
  },
  {
    id: 9,
    firstName: 'Olivia',
    lastName: 'Davis',
    age: 38,
    postalCode: '88-888',
  },
  {
    id: 10,
    firstName: 'David',
    lastName: 'Miller',
    age: 31,
    postalCode: '99-999',
  },
  {
    id: 11,
    firstName: 'Emma',
    lastName: 'Wilson',
    age: 29,
    postalCode: '10-010',
  },
  {
    id: 12,
    firstName: 'Matthew',
    lastName: 'Moore',
    age: 33,
    postalCode: '20-020',
  },
  {
    id: 13,
    firstName: 'Isabella',
    lastName: 'Anderson',
    age: 27,
    postalCode: '30-030',
  },
  {
    id: 14,
    firstName: 'Christopher',
    lastName: 'Taylor',
    age: 36,
    postalCode: '40-040',
  },
  {
    id: 15,
    firstName: 'Ava',
    lastName: 'Martin',
    age: 23,
    postalCode: '50-050',
  },
  {
    id: 16,
    firstName: 'Andrew',
    lastName: 'Harris',
    age: 37,
    postalCode: '60-060',
  },
  {
    id: 17,
    firstName: 'Mia',
    lastName: 'Clark',
    age: 24,
    postalCode: '70-070',
  },
  {
    id: 18,
    firstName: 'William',
    lastName: 'White',
    age: 34,
    postalCode: '80-080',
  },
  {
    id: 19,
    firstName: 'Ella',
    lastName: 'Turner',
    age: 39,
    postalCode: '90-090',
  },
  {
    id: 20,
    firstName: 'James',
    lastName: 'Smith',
    age: 41,
    postalCode: '01-001',
  },
];

export type User = (typeof userList)[number];
